name: Conditional Workflow
 
on:
  workflow_dispatch:
 
jobs:
  check-condition:
    runs-on: ubuntu-latest
    outputs:
      should-skip: ${{ steps.condition-checker.outputs.skip }}
    steps:
    - id: condition-checker
      run: |
        echo "::set-output name=skip::true"
 
  subsequent-job:
    needs: check-condition
    if: needs.check-condition.outputs.should-skip != 'true'
    runs-on: ubuntu-latest
    steps:
    - run: echo "This job runs if the condition is not met"
 
  another-job:
    needs: check-condition
    if: needs.check-condition.outputs.should-skip != 'true'
    runs-on: ubuntu-latest
    steps:
    - run: echo "This also runs only if the condition is not met"
